#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

PATTERN="^(feature|fix|hotfix|release|refactor|chore|develop)\/[a-z0-9]+(-[a-z0-9]+)*$"

if ! [[ "$BRANCH_NAME" =~ $PATTERN ]]; then
  echo "ERROR: Branch name '$BRANCH_NAME' does not follow the required pattern."
  echo "PATTERN: type/branch-description"
  echo "Example: feature/branch-description"
  exit 1
fi

exit 0